
#ifndef COMMON_TOOLS_CONSTANTS_H
#define COMMON_TOOLS_CONSTANTS_H

namespace commtools
{
double PI();
double LIGHT_VELOCITY();
double ELECTRON_CHARGE();
double ELECTRON_MASS();
double PROTON_MASS();
double VACUUM_PERMITTIVITY();
double NEUTRON_MASS();
double VACUUM_PERMEABILITY();
}
#endif // COMMON_TOOLS_CONSTANTS_H